export const names = [
  "Abyssinian",
  "Aegean",
  "Balinese",
  "Bambino",
  "Bengal Cats",
  "Burmese",
  "Burmilla",
  "California Spangled",
  "Chantilly-Tiffany",
  "Chinese Li Hua",
  "Cymric",
  "Devon Rex",
  "European Burmese",
  "Exotic",
  "German Rex",
  "Havana Brown",
  "Highlander",
  "Himalayan",
  "Japanese Bobtail",
  "Javanese",
  "Khao Manee",
  "Korat",
  "LaPerm",
  "Maine Coon",
  "Manx",
  "Napoleon",
  "Ocicat",
  "Oriental Bicolor",
  "Oriental",
  "Persian",
  "Russian Blue",
  "Selkirk Rex",
  "Serengeti",
  "Siamese Cat",
  "Sokoke",
  "Sphynx",
  "Tonkinese",
  "Toyger",
  "Ukrainian Levkoy",
];


export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "How it works", url: "/" },
      { title: "Featured", url: "/" },
      { title: "Partnership", url: "/" },
      { title: "Bussiness Relation", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "Events", url: "/" },
      { title: "Blog", url: "/" },
      { title: "Podcast", url: "/" },
      { title: "Invite a friend", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "Discord", url: "/" },
      { title: "Instagram", url: "/" },
      { title: "Twitter", url: "/" },
      { title: "Facebook", url: "/" },
    ],
  },
];
